all: undirectedGraphdriver

undirectedGraphdriver: undirectedGraphtest.cpp undirectedGraph.h undirectedGraph.cpp
	g++ -std=c++11 -o undirectedGraphdriver undirectedGraphtest.cpp undirectedGraph.cpp

clean:
	rm undirectedGraphdriver